# Generated by Django 2.2.4 on 2019-08-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=225)),
                ('news_web', models.CharField(max_length=225)),
                ('news_img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('authors', models.CharField(max_length=225)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.web2')),
            ],
        ),
    ]
