# Generated by Django 2.2.4 on 2019-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tb_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('jobtitle', models.CharField(max_length=225)),
                ('specialization', models.CharField(max_length=225)),
                ('Experince', models.CharField(max_length=225)),
            ],
        ),
    ]
